### ISSUE TITLE
Extension leaves a white box on page after closing

### ISSUE THREAD

**Issue by snyholm** [wolfie/PopupExtension#1] opened 2013-04-10 10:27 UTC
After calling extension.open() and then closing the extension, a small white (in my case) box is left floating around which moves when you scroll.

**Comment by wolfie** [comment] 2013-04-22 18:56
I can't reproduce this issue. A div with the class names "v-app reindeer v-overlay-container" seems to remain in the application after the popup is closed, but this seems to be a Vaadin-specific container DIV that contains also notifications and such items.

I'll close this for now. If you can find a minimal test case where this issue can be reproduced, feel free to reopen

**Closed as completed by wolfie** 2013-04-22 18:56 UTC
Labels: bug
